version: "3.9"

services:
  data-generator:
    build:
      context: ./data-generator
      dockerfile: Dockerfile
    container_name: data-generator
    volumes:
      - html-volume:/app/output
    restart: unless-stopped
    environment:
      - TZ=Asia/Seoul
      - KAKAO_API_KEY="KAKAO_API_KEY"
      - KAKAO_JS_KEY="KAKAO_JS_KEY"
    networks:
      - app-network

  web-server:
    build:
      context: ./web-server
      dockerfile: Dockerfile
    container_name: web-server
    ports:
      - "8080:80"
    volumes:
      - html-volume:/usr/share/nginx/html:ro
    depends_on:
      - data-generator
    restart: unless-stopped
    environment:
      - TZ=Asia/Seoul
    networks:
      - app-network

volumes:
  html-volume:
    driver: local

networks:
  app-network:
    driver: bridge
